routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:podcast
  /blog/:
    permalink: /{slug}/
    template: blog
    filter: tag:blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/